services:
  db:
    image: mysql:8.0
    container_name: mysql_e-learning_db_container
    ports:
      - "3307:3306"
    env_file:
      - ../.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - e-learning_app_network

volumes:
  mysql_data:

networks:
  e-learning_app_network:
    driver: bridge
